### PR TITLE
Fixes #42

### LINKED ISSUE #42: Uniqueness validation on enumerations field
You can't add uniqueness validation (normal or scoped to another attribute) on enumeration attribute.

```
class Order
  enumeration :status

  validates :status, uniqueness: true #this doesn't work
end

class Status < Enumerations::Base
  value :pending, name: 'Pending'
  value :finished, name: 'Finished'
end
```
This raises:
```
TypeError: can't cast Status
from /Users/infinum/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-5.1.5/lib/active_record/connection_adapters/abstract/quoting.rb:45:in `rescue in type_cast'
```

Fix:
```
class Status < Enumerations::Base
  value :pending, name: 'Pending'
  value :finished, name: 'Finished'

  def quoted_id
    id
  end

  def id
    symbol.to_s
  end
end
```

### PR DESCRIPTION
**Pull request by NBuhinicek**
#42

### CODE REVIEW

File: lib/enumerations/base.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@
 require 'enumerations/finder_methods'
 
 module Enumerations
-  class Base
+  class Base < ActiveSupport::Multibyte::Chars
```
Comment (PetarCurkovic) [inline lib/enumerations/base.rb]: It's ok, but you should add `super(symbol)` into #initialize to avoid warnings:
`/Users/petarcurkovic/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/multibyte/chars.rb:74: warning: instance variable @wrapped_string not initialized`

Comment (NBuhinicek) [reply lib/enumerations/base.rb]: Yes true, nice catch 👍
